application: python-django-practice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: endpoint.app_api.APPLICATION

libraries:
- name: django
  version: 1.5
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
